settings:
  parallel: true

driver:
  name: docker
  privileged: true

platforms:
- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    run_command: /usr/lib/systemd/systemd
    provision_command:
      - /bin/yum install -y initscripts net-tools wget
